### ISSUE TITLE
Why there are two copies of same program on different languages?

### ISSUE THREAD

**Issue by abenkovskii** [Felger/AutoPruner#9]
It looks like pruner.exe and pruner.pl are separate programs. Twice more bugs, twice more work, constant misssynchronization. Am I misunderstanding something?
P.S. Changing pruner.pl does not affect pruner behavior on windows.
P.P.S. Does anybody knows where to find source code of pruner.exe?

**Comment by Felger** [comment]
pruner.exe is a self-contained perl script that's built automatically from the pruner.pl, it's so you don't have to install Perl in windows to run autopruner.

pruner.pl is the source code for pruner.exe

**Comment by abenkovskii** [comment]
Now I understand.
